[package]
name = "kc_overlay"
version = "0.1.1"
edition = "2021"
authors = ["jafkc2"]
repository = "https://github.com/jafkc2/KC-Overlay"

[profile.release]
strip = true
lto = true

[dependencies]
iced = {version = "0.13.1", features = ["tokio"]}
reqwest = "0.12.12"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
